name: Tests

on:
  workflow_call:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean pycache
        run: |
          echo "🧹 Cleaning __pycache__ folders..."
          ind . -type d -name "__pycache__" -exec rm -r {} +

      - name: Run Pytest
        run: pytest -v
